### ISSUE TITLE
Support for newer Generac-branded systems?

### ISSUE THREAD

**Issue by tedtms** [mrworf/pika2mqtt#1]
Hey Henric,

First off, thanks for contributing this project! I stumbled upon it while looking for a way to integrate my PWRcell system (formerly the PIKA energy island) into my HomeAssistant or some other dashboard. Giving your script a test run, I found that the connection to my PWRcell beacon (which is just a raspberry pi!) was good and I was pulling statistics no problem. However, I ran into two issues:

1. At some point, Generac changed the Beacon behavior so that "Installer Mode" is disabled after minutes of inactivity **or** after like, 1 hour even if there is activity. The script would just stop getting responses from the Beacon after some time.
2. Polling the new https://pwrcell.generac.com site (which replaces the PIKA online dashboard but has the same content) for some reason does not work with the script. And yes I did make sure my dashboard was public. :)

I realize this project may not be at the top of your list anymore, but I was wondering if you've run into these issues since you first got it working and/or if you'd be able to help out at all. I sent a message to Generac asking if they know of a way to enable the Installer Mode permanently or even to just enable the web API on the LAN side (instead of the WiFi hotspot the Beacon creates when in Installer Mode), so we'll see how that goes.

Thanks!
Ted

**Comment by bdruth** [comment]
@tedtms - did you sort anything out? Trying to do the same thing, but for starters, I'm not seeing the same URL structure that the script is looking for ... i.e. there's not a `.json` file at the same location.

**Comment by tedtms** [comment]
@bdruth I did not, unfortunately. I figure Generac changed the site structure, but I also spoke to their support team and found out they're planning to overhaul the interface anyway.

**Comment by mrworf** [comment]
I might have some good news, depending on how adventurous you are. I've managed to unblock installer mode on the inverter which allow for local polling of data and a MUCH cleaner feed than scraping their site. Check out the [INSTALLER.md](https://github.com/mrworf/pika2mqtt/blob/master/extras/INSTALLER.md) in extras. Obvious disclaimer is that I don't take any responsibility should something go wrong, but regardless, thought I'd mention it 😸
